import { Destination } from './node';

/**
 * A lightweight, limited, msg implementation. Note that it lacks a dst argument
 * like normal mosi nodes because it ONLY sends a msg to the core (typically the
 * background page). The core will treat the msg as if was generated by a call
 * to msg() on the core itself. Thus, there is NO response handling.
 * 
 * This function is useful for avoiding code bloat loading the full mosi client
 * into frames that only need to send a simple one-off message for setup.
 * 
 * Saka Key (https://github.com/lusakasa/sakakey) loads a small setup script
 * into each frame, and if the frame is determined to be valid, uses this
 * to send a message to the background page, which loads the full Saka Key
 * content script using chrome.tabs.executeScript.
 */
export const msg = (action: string, arg: any): void => {
  chrome.runtime.sendMessage({
    t: 'msg',
    mosi_lw_msg: 1,
    action,
    arg
  });
};
